branches:
  only:
  - main

jobs:
 include:
 - name: Server
   language: csharp
   mono: none
   dotnet: 3.1.403
   solution: APRServer
   script:
   - dotnet new sln -n APRServer
   - dotnet sln APRServer.sln add **/*.csproj
   - dotnet restore
   - dotnet build
   - dotnet test lib/FacultyAPR.Storage.Blob/FacultyAPR.Storage.Blob.Tests/FacultyAPR.Storage.Blob.Tests.csproj
   - dotnet test lib/FacultyAPR.Models/FacultyAPR.Models.Tests/FacultyAPR.Models.Tests.csproj
 
 - name: Front-End
   language: node_js
   node_js: 14
   script:
   - cd FacultyAPR.Client/
   - npm ci
   - npm test -- --passWithNoTests
