export const CREATE_FORM = "CREATE_FORM";
export const UPDATE_SECTION = "UPDATE_SECTION";

export const UPDATE_REVIEW_SECTION = "UPDATE_REVIEW_SECTION";
export const UPDATE_STATE = "UPDATE_STATE"
export const UPDATE_REVIEW_COMMENT = "UPDATE_REVIEW_COMMENT"
export const UPDATE_FACULTY_COMMENT = "UPDATE_FACULTY_COMMENT"

